### ISSUE TITLE
fix: change the branch name from `Physics` to `Engineering Physics`

### ISSUE THREAD

**Issue by ashmitjsg** [rahul-gill/NITH-Result#2]
The correct branch name is `Engineering Physics`(B.Tech.) offered by the Department of Physics & Photonics Science.

**Comment by rahul-gill** [comment]
fixed in [a8b5d754501](https://github.com/rahul-gill/NITH-Result/commit/a8b5d754501813652a62d560356ed7dcdd9b1f56)
