### ISSUE TITLE
Could you add Gender filter

### ISSUE THREAD

**Issue by rajputrv** [rahul-gill/NITH-Result#8]
Not very much required but if possible, could you add gender filter. As hostel allotments are done with list of male only and female only basis, and better to know the rank. It an optional request.

**Comment by rahul-gill** [comment]
There's no way to identify gender other than doing it manually. Result website has no data about gender. Unless people are willing to provide that data, it's not possible.

**Comment by rajputrv** [comment]
Yeah got it. NO gender property in the json objects.  So  not possible.
